### ISSUE TITLE
Comments to the resources (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ziegm** [hl7ch/ch-etoc#55]
_Clinical content uses mostly the same resources as the IPS; some minor differences are explained in **comments** to the resources affected._ (Home)

Are these comments in the source (fsh-files)? If yes, it would be helpful to put them e.g. in the description of the profiles (and/or even as a separate section in the IG), so that they are visible/findable in the IG.

**Comment by JBleuer** [comment]
Added table 1 which lists all items with corresponding resources /datatypes

**Comment by JBleuer** [comment]
dropped "This IG follows the [Swiss eHealth Exchange Format Handbook Part I: Service Requests V 0.13](https://www.e-health-suisse.ch/fileadmin/user_upload/Dokumente/E/Exchange-format-handbook_part-1_v12.pdf). The Questionnaire resource gives guidance for the implementation of the user interface." 
Reason: Due to the decision, to make the Questionnaire mandatory, the Handbook needs to be updated and "The Questionnaire resource gives guidance for the implementation of the user interface" does not make sense any more.

**Comment by pjolo** [comment]
Ok for me
